default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DATABASE_NAME'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] || 5433 %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>_development

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>_test

staging:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>_staging

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>_production
